### ISSUE TITLE
Unsummon doesn't work when eidolon is at negative HP

### ISSUE THREAD

**Issue by Truinto** [Holic75/KingmakerRebalance#18]
If an Eidolon is at 0 or less HP, the Unsummon ability stops working. Tested it out of combat, in combat, turn based, and real time. Doesn't matter. Also is not connected to the prone condition, at least when applied through Bag of Tricks.

Pretty sure it's due to UnitPartUnsummonedCompanion Line 320. Also not sure why there is companion_hp variable. Note that having the companion unconscious vs dead is important, since the Summon Monster doesn't work while the Eidolon is alive.

**Comment by Holic75** [comment]
This is intended.

**Comment by Truinto** [comment]
I am sorry. I didn't explain it very well. I will give an example.

1) Eidolon at 10 HP.
2) Enemy hits Eidolon for 15 damage. Eidolon falls over, but isn't dead.
3) Summoner casts 'Unsummon Eidolon'. His Standard Action is wasted, but the Eidolon is still active/alive.

Remark that the ability itself can be used, it just doesn't do anything.
