### ISSUE TITLE
Lore and Ascetic mysteries for oracles.

### ISSUE THREAD

**Issue by rilian-la-te** [Holic75/KingmakerRebalance#23]
Lore spirit is already in game, but lore mystery is not.

Ascetic mystery just turn Oracle into casting Monk with some flavour abilities (reference: https://aonprd.com/MysteryDisplay.aspx?ItemName=Ascetic)

Will it be added into this mod?

**Comment by rilian-la-te** [comment]
Also an enlighted paladin is good and follow a monastic theme too (for Irori)
https://www.d20pfsrd.com/classes/core-classes/paladin/archetypes/paizo-paladin-archetypes/enlightened-paladin-paladin-archetype

**Comment by rilian-la-te** [comment]
So, will it be implemented? What is a resolution of an feature request?

**Comment by Holic75** [comment]
No, it will not be implemented.

**Comment by rilian-la-te** [comment]
Thanks for clarification.
