### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Mecar1997** [Holic75/KingmakerRebalance#24]
* Dueling Sword Proficiency
"An dueling sword" -> "A dueling sword"

* Estoc proficiency
First half of the description mentions the dueling sword instead of estoc
This is because the code is "estoc_proficiency.SetDescription(dueling_sword_proficiency.Description + ..." instead of "estoc_proficiency.SetDescription(estoc_proficiency.Description + ..."

* Fighter Armor Specialization
 Name is ""Armor Specializaiton", should be "Armor Specialization"

* Intensified Metamagics
Shows up as "Intesnsified" in tooltip description.
Issue: MetamagicFeats.cs line 1071 should be 'extra_metamagic += "Intensified, ";'

* Warpriest.cs
warpriest_spontaneous_harm mentions the cleric class instead of warpriest class

**Comment by Holic75** [comment]
Thanks
