### ISSUE TITLE
Note about Nature Relevation difference.

### ISSUE THREAD

**Issue by rilian-la-te** [Holic75/KingmakerRebalance#25]
Friend of the Animals does not give Nature's ally spells, it is commented (regression in https://github.com/Holic75/KingmakerRebalance/commit/a0ffce3a5fdcd124b705f8fd85b07c6d4b6d6343).

If it is intended, please, note it in README. If this is not intended, please, give back this abilitiy.

**Comment by Holic75** [comment]
It is not supposed to give these spells. Reread pnp description one time.
