### ISSUE TITLE
Original game bug fixes only

### ISSUE THREAD

**Issue by goodandrewsoft** [Holic75/KingmakerRebalance#3]
> Original game bug fixes:
>     Vital Strike now takes standard action and extra damage dice are no longer multiplied on critical hits,
>     Singing Steel works properly,
>     Archaeologist luck works with Lingering Performance and Singing Steel,
>     Lingering Performance no longer allows to overlap different bardic performances,
>     Summoned weapons no longer consume additional standard action on equip,
>     Dazzling display can no longer be used without weapon for which you have weapon focus,
>     Dragonkind I dragons bite and claw weapon are placed in main/off hand slots (so it can benefit from haste and feral combat training),
>     Web school is changed to conjuration,
>     radius of teamwork feats that require "adjacent" allies changed to 5 feet (instead of 5 meters) (optional),
>     Invulnerable rager extreme endurance bonus no longer scales exponentially,
>     Unarmed bonuses from Magic fang, Manticore's gloves and amulet of mighty fists should no longer stack,
>     Characters now receive slam natural weapon proficiency,
>     Fixes incorrect calculation of burn cost for kinetic blade and blade whirlwind abilities.
>     necklace of double crosses no longer gives sneak attack bonus on ranged attacks,
>     Fixed issue where certain domains (mostly for druids) did not allow to use non-domain spells if they had lower level than that on
>     domain list (respec is required),
>     Polymorph no longer puts a lock on inventory slots (they still stay inaccessible though) to avoid preventing temporary weapons and limbs
>     from removal when corresponding buffs expire; as a side effect it is also possible now to loot body under baleful polymorph.
> 

How add only this in mod?

**Comment by Holic75** [comment]
All optional components are specified in settings.json file. Everything else is mandatory.

**Comment by goodandrewsoft** [comment]
That is not answer on my question
