### ISSUE TITLE
Warpriest Fervor typo with Balance Fixes on

### ISSUE THREAD

**Issue by Mecar1997** [Holic75/KingmakerRebalance#34]
with balance fixes toggled on, Warpriest's Fervor reads "plus an additional 1d68 points of damage".

This is because the description is set to "1d6{BalanceFixes.getDamageDieString(DiceType.D6)}" instead of "1d{BalanceFixes.getDamageDieString(DiceType.D6)}"

**Comment by Holic75** [comment]
fixed
