### ISSUE TITLE
Antipaladin Typos

### ISSUE THREAD

**Issue by Mecar1997** [Holic75/KingmakerRebalance#37]
Unholy Minion's domain selection's description: "...domain spell slot for each level of paladin spells she can cast" should reference antipaladin levels rather than paladin

Smite good: "The smite good lasts until the target dies or the paladin selects a new target. At 4th level, and at every three levels thereafter, the paladin may smite good one additional time per day." should reference the antipaladin instead of paladin (twice).

**Comment by Holic75** [comment]
fixed
