### ISSUE TITLE
Divine Anger

### ISSUE THREAD

**Issue by Mecar1997** [Holic75/KingmakerRebalance#39]
* Divine Anger seems to give +1 more than it should. The ability says "You can rage for a number of rounds equal to your wisdom modifiers PLUS 1 per inquisitor level ABOVE 4. At level 6 I had 7 rounds even though i only had 4 wisdom modifier and 2 levels above 4 (level 5 & 6).

* Divine Anger can be used to get the Extra Rage feat but the feat doesn't give bonus Divine Anger rounds (since Divine Anger uses a different resource that's separate from other rages).

**Comment by Holic75** [comment]
fixed
