### ISSUE TITLE
Arcanist buff CL/DC does not spend arcane reservoir points

### ISSUE THREAD

**Issue by inversemot** [Holic75/KingmakerRebalance#4]
It appears that the unlettered archetype overrides the spellbook for the Arcanist so other types of Arcanist no longer are considered to be casting a spell out of the correct spellbook. I would guess that only one instance of a given Component can be added and the following lines override everything else.

`dc_buff.AddComponents(Helpers.Create<NewMechanics.IncreaseAllSpellsDCForSpecificSpellbook>(i => { i.spellbook = unlettered_arcanist_spontaneous_spellbook; i.Value = Helpers.CreateContextValue(AbilityRankType.Default); }),
                                  Helpers.Create<NewMechanics.SpendResourceOnSpellCast>(s => { s.spellbook = unlettered_arcanist_spontaneous_spellbook; s.resource = arcane_reservoir_resource; })
                                  );
            cl_buff.AddComponents(Helpers.Create<NewMechanics.IncreaseAllSpellsCLForSpecificSpellbook>(i => { i.spellbook = unlettered_arcanist_spontaneous_spellbook; i.Value = Helpers.CreateContextValue(AbilityRankType.Default); }),
                                  Helpers.Create<NewMechanics.SpendResourceOnSpellCast>(s => { s.spellbook = unlettered_arcanist_spontaneous_spellbook; s.resource = arcane_reservoir_resource; })
                                 );`

In my local game, I'm just going to have it always spend the points on spell cast... don't know if that will work out, just started hacking on your code because I wanted to implement a blade adept style archetype for arcanist.

**Comment by Holic75** [comment]
I could not confirm it as of version 1.65d.
