### ISSUE TITLE
Incorrect damage description with balance fixes on.

### ISSUE THREAD

**Issue by Mecar1997** [Holic75/KingmakerRebalance#40]
With balance fixes on, the description of the following is incorrect:

Grave Touch (Bone Spirit): The ability correctly mentions it does 1d6 (rather than 1d4) damage but the description on the feat (as shown in the class progression UI) still says 1d4.

Hex Channeler: The Channel feat (on class progression UI) still mentions 1d6. The hex that increases the damage die also mention 1d6 rather than 1d8.

**Comment by Holic75** [comment]
fixed
