### ISSUE TITLE
Warpriest & Versatile Channeler feat

### ISSUE THREAD

**Issue by Mecar1997** [Holic75/KingmakerRebalance#41]
Looking at the source code, it looks like Versatile Channeler won't work for warpriests who channel negative energy ?

Code is
```
Common.createAddFeatureIfHasFactAndNotHasFact(Warpriest.channel_positive_energy, Warpriest.channel_negative_energy, versatile_channeler_negative_warpriest),

Common.createAddFeatureIfHasFactAndNotHasFact(Warpriest.channel_negative_energy, Warpriest.channel_negative_energy,versatile_channeler_positive_warpriest),
```

The second 'createAddFeatureIfHasFactAndNotHasFact' function has "Warpriest.channel_negative_energy" twice, which doesn't match how the cleric part of the feat is done ?

**Comment by Holic75** [comment]
fixed
