### ISSUE TITLE
Havocker Witch - Fire Blast

### ISSUE THREAD

**Issue by Mecar1997** [Holic75/KingmakerRebalance#42]
Using the Havocker Witch and getting Fire as my patron element, I was unable to use Fire Blast. This is because I get the 'Fire Blast' ability but clicking on it does nothing (Supposedly this is supposed to open another window where I can select the fire blast ability, just like the Kineticist but this ability is missing).

EDIT: This is also the case for Water Blast. I assume it's bugged for all blasts.

**Comment by Holic75** [comment]
fixed
