### ISSUE TITLE
Ever since  Version 1.134-2.1, can't see most class selections

### ISSUE THREAD

**Issue by mattheweigand** [Holic75/KingmakerRebalance#46]
I've noticed something as I've been updating this mod, and I looked into it in detail today. I completely uninstalled Pathfinder Kingmaker, reinstalled it, installed Unity Mod Manager, and then the latest version of this mod. When in the new character creation screen, I can't see most character choices. 

I went back and installed older versions of the mod until I got back down to 1.133b-2.1. After installing that version I was able to see all the class selections again.

In specific detail, the class selection window when I look at the 1.133b-2.1 version starts out like this: Alchemist, Animal, Anitpaladin, Arcanist. 

When I look at the class selection window with a later version of the mod installed, the first 4 choices are: Alchemist, Antipaladin, Barbarian, Bard.

**Comment by Holic75** [comment]
I am unable to reproduce the issue

**Comment by mattheweigand** [comment]
I'm on Linux, perhaps that is a factor? I once had an obscure bug with another mod in another game due to the different way linux and windows arrange capital and lowercase files, so files were loading up in the wrong order on Linux. I'll try to see what changed between versions and how it loads up in linux.
