### ISSUE TITLE
Kinetic Whip wild talent on Kinetic Knight doesn't always give AoOs or reach

### ISSUE THREAD

**Issue by swwu** [Holic75/KingmakerRebalance#47]
**Game version:** 2.1.5d

**Enabled Mods:**
* Call of the Wild (1.13.6b-2.1)
* Proper Flanking 2 (1.2.2-2.1)
* Bag of Tricks (1.16.2)

**Issues:** In turn-based mode, the Kinetic Whip wild talent for Kinetic Knight only grants reach and AoOs when using the "Charge" ability, or when gather power is used. It doesn't gain reach or allow AoOs when full attacking, or when standard action attacking without gather power.

**Details for replicating the bug:**
Race: human
Class: Kineticist (Kinetic Knight)

Level 1:
Feat: Toughness
Feat: Shield Focus
Elemental Focus: Fire
Infusion: Dazzling Infusion

Level 2:
Wild Talent: Elemental Whispers (Lizard)

Level 3:
Feat: Weapon Focus (Kinetic Blast)

Level 4:
Wild Talent: Fire's Fury

Level 5:
Feat: Iron Will

**Dropbox link for game saves for your testing:**
Kinetic Knight 6 in Endless Dungeon
https://www.dropbox.com/s/zn1nm821q838zxw/Manual_36_Tenebrous_Depths__I___14_Gozran__IV__4710___12_01_21.zks?dl=0

**Comment by Holic75** [comment]
fixed
