### ISSUE TITLE
Blood Hunter Hunter´s Bond issue

### ISSUE THREAD

**Issue by veidral** [Holic75/KingmakerRebalance#49]
Game version: 2.1.5d

Enabled Mods:

Call of the Wild (1.137-2.1)
Bag of Tricks (1.16.2)

Issue: According to the ability description of Favored Target, "Additionally, the favored target ability always grants or uses a minimum of the blood hunter’s full favored target bonus for the purposes of effects that use the value of the ranger’s favored enemy bonus. For example, a blood hunter grants his full favored target bonus to his companion when using the hunter’s bond class feature." 

If a pet is chosen the pet gets the favored target bonus as it should, However, if the other option is chosen where the ranger can share his bonuses with his allies, the buff they get is at half effect. 

Details for replicating the bug:
Level Blood Hunter to level 5, grab non-pet Hunter´s Bond at level 4. 
Attack random opponent with buff applied and check combat log, the Blood hunter gets the full bonus but other characters only receive half the benefit. 

Link to savegame with a level 5 Blood Hunter : 
[Manual_2_Jamandi_Aldori_s_Mansion___15_Gozran__IV__4710___12_01_58.zip](https://github.com/Holic75/KingmakerRebalance/files/6341096/Manual_2_Jamandi_Aldori_s_Mansion___15_Gozran__IV__4710___12_01_58.zip)

**Comment by Holic75** [comment]
"his companion" means his animal companion in this context,
The ranger can not share favored enemy bonus via allies bond with "his companion", he shares it with "all his allies".

**Comment by veidral** [comment]
I hate to argue, but that´s not the most relevant part of the quoted passage. 

Standard allies bond is an effect that uses the value of the ranger´s favored enemy bonus, in this case half. 

According to the text, all those effects for the blood hunter always use the full favored target bonus. 

Your argument makes no sense since all rangers with pet share the full favored enemy bonus with them anyway, there would be no reason for the archetype text to mention that then.
