### ISSUE TITLE
Sacred Fist AC Bug

### ISSUE THREAD

**Issue by magee101** [Holic75/KingmakerRebalance#51]
Hello there! I'm currently using 1.135 of the mod (and only have this mod and Unity Mod Manager installed) and most current version of vanilla game, and I don't see this problem in your changelog, not sure how to report it as bug on Nexus Mods so I am bringing it here.

The Sacred Fist Archetype for the War Priest states that it gets Wisdom Modifier to AC. In vanilla game there is sometimes a bug that the Wisdom Mod does not apply to AC for monks in the character sheet screen, but it will still correctly be represented in game when you hover over dice rolls. For the Sacred Fist archetype added by this mod:

A) it does not show the increase to AC from Wisdom Modifier in the character sheet

B) It does not show the increase to AC from Wisdom Modifier in dice rolls made against the character that has levels in Sacred Fist

C) The character is Harrim, who has a +3 Wisdom Mod by default with no changes.

D) If an enemy NPC rolls over the reflected AC, they hit, so there is no somehow invisible buffer to AC, Wisdom Mod is just simply not applying. 

E) The +1 AC bonus that is part of the same effect that should be giving Wisdom Bonus (as well as the +1) is working, as there is a +1 Other Bonus listed in the character's AC info. 

The character is not wearing armor and is under light load (as of writing this I had stripped him of literally all equipment and he was shown as carrying 10lbs. still no AC bonus from wisdom) 

The party is considered light load when checking AC and enemy rolls.

**Comment by Holic75** [comment]
Read mod description till the end.

**Comment by magee101** [comment]
Sorry, I'm not sure what you mean by that. I've read the mod description through, there is no Wisdom bonus to AC, it is not even getting the level-restricted +1 (if it was, as per the wording of the feature it would be +1 Wisdom bonus and +1 other bonus for a total of +2 to AC)

However, Harrim is only receiving +1 to AC from the bonus from the feature, and there is no Wisdom being added, and it is above and beyond the Vanilla Bug because the Vanilla bug is purely cosmetic, but it still mechanically represented for Monks. This Sacred Fist added by your mod (and your mod is only mod running and installed) is not calculating the Wisdom Bonus even at the limited "optional balance" level

**Comment by Holic75** [comment]
Now reread corresponding AC bonus ability till the end and calculate what your total dodge AC bonus from it should be at lvl 1.

**Comment by magee101** [comment]
According to the Sacred Fist ability, the Sacred Fist gains Wisdom modifier to AC (optional balance makes this restricted to level) and a +1 bonus, gaining an additional +1 every four levels (+2 at lvl 8 etc).

With these factors, Harrim's level 1 AC should be (10+2 Dex Mod+1 Wisdom Mod (restricted)+1) 14

However, your mod is calculating (10+2 Dex Mod +1) 13

**Comment by Holic75** [comment]
I think you have serious issues understanding written information.  Please do not make any more bug reports in the future, until someone certifies that the issue is resolved.

**Comment by magee101** [comment]
Excuse me? I am not understanding where this hostility is coming from. You asked me "Now reread corresponding AC bonus ability till the end and calculate what your total dodge AC bonus from it should be at lvl 1."

I showed you the text of the ability and then the appropriate calculations including the subtext information from the description of the mod with the optional balance changes. I do not understand how I could be any clearer in my communication. I cannot be any more plain in my communication regarding the situation except for to ask YOU to go read the Sacred Fist yourself.
