### ISSUE TITLE
Bug with Charge reporting with Balance Changes off

### ISSUE THREAD

**Issue by MangledMouse** [Holic75/KingmakerRebalance#52]
When the game is run with balance_fixes set to false the game often does not show the attack description for the attack associated with the Charge action on hits. Weirdly attacks that miss still output the appropriate line consistently.

Steps to reproduction
Set balance_fixes to false
Charge an enemy or let one charge you (for testing purposes you can charge an ally)
Have that hit
Notice that the line "(attacker) attacks (target) with (Attack) Hit" does not appear after the "(attacker) uses ability: Charge" line

This process does not produce the behavior 100% of the time as visible in this screen cap. I have not been able to reproduce the behavior with balance_fixes off.

![charge weirdness](https://user-images.githubusercontent.com/1857093/116437998-061c4a00-a81c-11eb-8d65-811bb1a39155.png)

This was produced with the Proper Flanking, Favored Class and KingmakerAi mods on in case that might be relevant

**Comment by MangledMouse** [comment]
Here is a save with this issue present

![Manual_85_Save_for_Holic](https://user-images.githubusercontent.com/1857093/116568983-f7469d80-a8d6-11eb-845a-bddc4e2bc637.gif)

that needs to be changed to a .zks file to be loaded as a save (github didn't let me update it as a zks)

**Comment by Holic75** [comment]
I am unable to reproduce the issue even with your save file.
