### ISSUE TITLE
Urban Skald Controlled Inspire Rage prevents affected allies from using Intelligence-, Dexterity-, or Charisma-based skills.

### ISSUE THREAD

**Issue by theMangoose** [Holic75/KingmakerRebalance#53]
Not sure if this is a bug, as your tooltip reads different from PNP, ending right before that, but I suppose I'll mention anyways because I didn't see it in your "changes from pnp" list.

**Comment by Holic75** [comment]
I am unable to reproduce the issue. In case you does not know, there is a faq on cotw page explaining how to make a proper bug report.
