### ISSUE TITLE
Spellshield and Contingency do not work with Controller UI.

### ISSUE THREAD

**Issue by nstgc** [Holic75/KingmakerRebalance#56]
When attempting to store a spell with the Skirnir's Spellshield ability or the Contingency spell, no option to do so appears for valid spells. This works fine for me when using KB+M, however due to a wrist injury, I can't use a mouse for extended periods of time. This means I have to play this exclusively with a controller.

Steps to reproduce:

Create a Skirnir with 12+ INT in Beneath the Stolen Lands; level up to 7, making sure to select Acid Arrow; rest; add Acid Arrow to your hot bar; move the selector box/cursor over Acid arrow and press up to access the spell options. You will only have a greyed out option to use your Arcane Bond -- Object.

**Comment by nstgc** [comment]
More information.

Sorry, for sending more your way, but I realized there was a PF:KM patch today. This is not a new issue for me. It's just that I only now was able to work with someone else to try to identify what I was doing wrong.

My game version is 2.1.7, and this issue has been present on both versions 1.141 and 1.142.

**Comment by Holic75** [comment]
fixed
