### ISSUE TITLE
Havocker's Spellburn's description doesn't match what's on the mod page.

### ISSUE THREAD

**Issue by nstgc** [Holic75/KingmakerRebalance#57]
![Screenshot from 2021-05-20 20-09-27](https://user-images.githubusercontent.com/25557355/119063805-f372dc00-b9a7-11eb-91a6-e7f2e85ce27e.png)

From the mod page for the ability:
> Havocker was a bit reworked, she receives infusions at level 4 and every 4 levels therafter, **spell burn at level 6**, can gather energy as kineticist starting, and receives infusion specialization at levels 10, 14 and 18,  **spellburn allows to reduce burn cost by 1 per 2 spell levels**.

In game, the ability is granted at level 6, matching the mod page description. I was unable to confirm the second part about burn being reduced by twice the spell level. That is a separate issue that requires further testing, however I will state that the Spellburn ability is not showing up in the ability menu in either the KB+M UI nor in the Controller UI. It does show in the Character Sheet. Aside from Bag of Tricks (for "Always able to Level"), I am not using any mods. I do want to confirm this with someone else before submitting a formal bug report though.

Mod version: 1.142
Game version: 2.1.7

Steps to reproduce: Start a new game in Beneath the Stolen Lands; select Havock Witch and examine the class abilities; "mouse over" Spellburn.

**Comment by nstgc** [comment]
I've formatted a patch to address this if you feel it's appropriate:

```
From 344ff04f6c9c7119f4c8549b0de74cd0376c879d Mon Sep 17 00:00:00 2001
From: nstgc <please.spam.now@gmail.com>
Date: Thu, 20 May 2021 20:34:52 -0400
Subject: [PATCH] fixed description for Spellburn

---
 CallOfTheWild/Classes/Witch.cs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/CallOfTheWild/Classes/Witch.cs b/CallOfTheWild/Classes/Witch.cs
index 765bdb1..0d2f01b 100644
--- a/CallOfTheWild/Classes/Witch.cs
+++ b/CallOfTheWild/Classes/Witch.cs
@@ -779,7 +779,7 @@ namespace CallOfTheWild
             {
                 var buff = Helpers.CreateBuff($"SpellBurn{i}Buff",
                                               $"Spellburn ({i/2})",
-                                              "Beginning at 4th level, a havocker can channel stored spell energy into her kinetic blast to increase the blast’s overall utility and power. To use her infusions, the havocker must lose a prepared witch spell to apply the infusion to her kinetic blast. Any spell sacrificed is required to have a spell level equal to at least twice the infusion burn cost. The havocker cannot accept additional burn if the infusion would allow her to do so.",
+                                              "Beginning at 6th level, a havocker can channel stored spell energy into her kinetic blast to increase the blast’s overall utility and power. To use her infusions, the havocker must lose a prepared witch spell to apply the infusion to her kinetic blast. Any spell sacrificed is required to have a spell level equal to at least half the infusion burn cost rounded up. The havocker cannot accept additional burn if the infusion would allow her to do so.",
                                               "",
                                               icon,
                                               null,
-- 
2.31.1
```

**Comment by Holic75** [comment]
fixed
