### ISSUE TITLE
Game fails to enter game world when starting the game as a Necroccultist

### ISSUE THREAD

**Issue by nstgc** [Holic75/KingmakerRebalance#59]
When attempting to start a new game of Beneath the Stolen Lands as a Necroccultist, the game returns the player the main menu upon completion of character creation. This does not effect the generic Occultist, even when choosing a Necromancy implement and the Soulbound Puppet. I'm using CotW v1.143 and PF:KM v2.1.7.

Steps to reproduce: Start a new game as a Necroccultist and finish rolling your character.

No mods (including Bag of Tricks) were used.

I've attached the UMM logs.

[Necroccultist_Fail.txt](https://github.com/Holic75/KingmakerRebalance/files/6525097/Necroccultist_Fail.txt)

**Comment by nstgc** [comment]
Creating a new companion is fine. Similarly, you can start as something else, and then level up as a Necroccultist.

**Comment by nstgc** [comment]
Sorry for yet another message, but my work around doesn't work. You can't load a save with a character possessing levels in Necrocultist it seems. I believe the file below is a good example save.

[IronMan_123.zks.zip](https://github.com/Holic75/KingmakerRebalance/files/6525278/IronMan_123.zks.zip)

I'm done. I won't bother you again regarding this. I just wanted to make sure you had as much info as possible to help resolve the issue.

**Comment by Holic75** [comment]
Play on windows. Use mouse + keyboard. I will not work on linux/controller support since I have no interest.
