### ISSUE TITLE
Animal Companions Broken

### ISSUE THREAD

**Issue by dredgemage** [Holic75/KingmakerRebalance#6]
When I create a character with an animal companion it creates them as a character I need to manually level up. When I go to level them up (I assume this would be the use for the "Animal" class) it has me create a whole new character; select a portrait, race, class, etc.

**Comment by Holic75** [comment]
Update game to 2.08, remove all other mods.

**Comment by dredgemage** [comment]
Confirmed that updating to 2.0.8 fixed the issue. Thanks for the quick response.
