### ISSUE TITLE
Occultist spellcasting appears broken for spells level above 0

### ISSUE THREAD

**Issue by nstgc** [Holic75/KingmakerRebalance#60]
The issue with Occultist spellcasting appears to be two fold.

First, on level up, an Occultist is not being asked to select spells. There is the exception of the Necrocultist, but that appears to be for bonus wizard spells.

Second, when the spell book is filled via Bag of Tricks, the spells do not show in the pop-up spell menu from the action bar (when using the KB+M UI) and adding the spells to the action bar when using the Controller UI produces an "empty" icon. I believe this is the same behavior seen in https://github.com/Holic75/KingmakerRebalance/issues/59. Upon saving and reloading, all spells are removed from the spell book.

![Screenshot from 2021-05-21 19-31-48](https://user-images.githubusercontent.com/25557355/119207208-7741cc80-ba6b-11eb-8411-c3de0491e446.png)

I have not confirmed this with another player due to the added security on the Discord channel I was using blocking my ability to post (it requires I give them my phone number, something I'm unwilling to do).

I did not try this prior to the v2.1.7 PF:KM update. Similarly I have not tried with previous versions of CotW.

**Comment by Holic75** [comment]
Play on windows. Use mouse + keyboard. I will not work on linux/controller support since I have no interest.
