### ISSUE TITLE
Bugs on my version

### ISSUE THREAD

**Issue by pblack476** [Holic75/KingmakerRebalance#61]
Sorry for posting this bug report here but on Nexus it was not possible to open a new issue on the bugs tab.

The mod does not seem to be working as intended for me. None of the regular classes's archetypes are available at all and a few that are, are somewhat broken. Hunter being one where animal companion while leveling up does not let me select animal class, instead being locked into "kineticist" or "slayer" and it justs wrecks the whole point of picking hunter. This also breaks regular ranger's animal companions in the same manner. Behaviour is gone after I remove the mod.

Now, I AM on Linux and you probably do not offer support for linux users. But at least here is my report so you know how it performs on the platform. I was using 2.1.5b version and the issue was present there, now the game updated to 2.1.7 but there was no change, of course I wouldn't expect it to work on a different version of the game, but the problem was already present on 2.1.5b. 

No other mods installed while testing this.

**Comment by Holic75** [comment]
It is written in the description that mod is only expected to work correctly on windows.
