### ISSUE TITLE
Consider making animal companion manual level up optional

### ISSUE THREAD

**Issue by pblack476** [Holic75/KingmakerRebalance#62]
Hi. Considering that Linux in unsupported would you consider at least making the animal companion manual level up component optional on future releases? This would make it so the mod at least does not break anything for linux users. It would have missing features but none of the features that work would harm the experience in any way. I figured this would be easy enough to implement without actually going through the trouble of offering full support for linux users. Thank you for the attention and hard work you've done.

**Comment by Holic75** [comment]
Please read mod description and faq on nexus page (probably several times, until you are confident that you understood everything), do not make any bug reports until you do so.

**Comment by nstgc** [comment]
@pblack476 In the monolithic README, it states that this is an optional component to the mod.

What you do is go to your PF:KM installation directory and go to `Mods/CallOfTheWild/settings.json` and change line 2 `"update_companions": true,` to "false".

So as not to reopen another issue, I'd also like to address https://github.com/Holic75/KingmakerRebalance/issues/61. This is largely what I was talking about regarding https://github.com/Holic75/KingmakerRebalance/issues/55.

What I ended up having to do was use the Windows version, however as of mod version 1.143 the mod is almost completely borked when run this way so you'll want to use 1.142. Even there there are a number of things that are broken, but it is mostly working.

I'd very much like to have another Linux user I could try troubleshooting these issues with, so please contact me on Discord at krovoc#1068.

**Comment by Holic75** [comment]
update_companions does not affect animal companions in any way, it is for npc. If the mod had "a number of things that are broken", people would be crying on every corner that the mod is broken, which is not the case, so the issue is on your side. Really stop spamming, otherwise I will have to make this repository private.
