### ISSUE TITLE
Oracle curse Deaf won't remove Perception penalty @ level 5

### ISSUE THREAD

**Issue by AlonsoCagi** [Holic75/KingmakerRebalance#64]
As title says, respeced main charcater to Oracle, Time mystery w/Deaf curse and on level 5 and beyond the Perception penalty still applies. Out of curiosity checked your code here on CalloftheWild/Classes/Oracle and indeed starting on line 2705:

var curse5 = Helpers.CreateFeature("OracleCurse5Deaf", 
                                               curse.Name,
                                               "At 5th level, you no longer receive a penalty on Perception checks, and the initiative penalty for being deaf is reduced to –2.",
                                               "",
                                               curse.Icon, FeatureGroup.None,
                                               Helpers.CreateAddStatBonus(StatType.Initiative, 2, ModifierDescriptor.UntypedStackable)
                                               );
      
As you can see it doesn't include the Perception penalty removal. An update would be greatly appreciated.

**Comment by Holic75** [comment]
fixed
