### ISSUE TITLE
Class Ability Issue

### ISSUE THREAD

**Issue by Kainpillars** [Holic75/KingmakerRebalance#65]
Pathfinder: Kingmaker ability issue for Unchained Monk. I'm using the Call of the Wild and Favored Bonus mods as well as Respecialization and Craft Magic Items. After running tests, the issue only persists with Call of the Wild. 

Via the Mod, the Unchained Monk's AC Bonus ability is affected by level (wording is similar to "AC bonus equal to Wisdom, up to monk level"). The issue with this is that the ability, as per PnP as well as in the base game, does not work in this manner. The ability is worded as, "When unarmored and unencumbered, the monk adds his Wisdom bonus (if any) to his AC and CMD. In addition, a monk gains a +1 bonus to AC and CMD at 4th level. This bonus increases by 1 for every four monk levels thereafter, up to a maximum of +5 at 20th level. These bonuses to AC apply even against touch attacks or when the monk is flat-footed. He loses these bonuses when he is immobilized or helpless, when he wears any armor, when he carries a shield, or when he carries a medium or heavy load."

**Comment by Holic75** [comment]
Read mod description.
