### ISSUE TITLE
Skirnir Magus delivers touch spells twice in single attack

### ISSUE THREAD

**Issue by Xerlith** [Holic75/KingmakerRebalance#66]
![image](https://user-images.githubusercontent.com/10631248/120123106-4a995d80-c1ad-11eb-82b4-84054d20c5e2.png)
![image](https://user-images.githubusercontent.com/10631248/120123120-5422c580-c1ad-11eb-9b8d-9b4ef1424571.png)

Magus with the Skirnir archetype can deliver the held/cast spell twice. 

1. Get Shield Bash and enable it
2. Equip a Shield but not a weapon
3. Cast a touch spell on a hostile target with Spellstrike enabled

There will be an unarmed attack followed by two applications of the spell.

**Comment by Holic75** [comment]
Can't vanilla magus do the same in base game?
