### ISSUE TITLE
Halcyon spell lore is too permissive

### ISSUE THREAD

**Issue by Bobsson** [Holic75/KingmakerRebalance#67]
The description of the Arcanist ability Halcyon Spell Lore says that the available spells "cannot be a spell that already appears on the arcanist spell list".  However, the actual list of spells includes some that are available to the character normally, such as Flaming Sphere (and greater) and Cloak of Winds.  

I don't know if the description is wrong or the spell lists are, but there's definitely a disconnect.

**Comment by Holic75** [comment]
fixed
