### ISSUE TITLE
The Shield Master feat functions normally as in version 1.82c

### ISSUE THREAD

**Issue by liuruixing** [Holic75/KingmakerRebalance#7]
Well, since you closed the post/bug area on the nexusmods site, I can only submit my feedback here, hope I am not bothering you too much.
Why did you close them?

**Comment by Holic75** [comment]
Well, mostly because I receive a lot of useless reports, which are not bugs at all, and there is nothing I can do about it.
Feel free to post any issues here if you need.

**Comment by liuruixing** [comment]
> Well, mostly because I receive a lot of useless reports, which are not bugs at all, and there is nothing I can do about it.
> Feel free to post any issues here if you need.

Thanks for the excellent content you have created and diligently maintained!
