### ISSUE TITLE
Brawler's Offhand Unarmed Attacks

### ISSUE THREAD

**Issue by Mecar1997** [Holic75/KingmakerRebalance#70]
Toggling the "Unarmed Strike Off-hand attacks" or "Brawler's Flurry: Use offhand attacks" counts as a "weapon change" action and removes your Move Action for the turn (or Standard action if you already used a move action)

**Comment by Mecar1997** [comment]
In addition:
* Brawler has to choose between TWF and flurry of blows. From what I understand, a brawler with 11 BAB should be able to do 3 offhand attacks + 3 mainhand attacks + 1 flurry of blow with a hand of his choosing, meaning 7 attacks, but right now you can either do 4 attacks (3 mainhand + flurry of blows) or 6 attacks (3 mainhand + 3 offhand). I'm not every familiar with PnP rules so do correct me if I'm wrong.

* Offhand attacks do not play an animation (atleast in turn-based mode). Its a minor issue and doesn't impact gameplay.

**Comment by zVcXr** [comment]
AFAIR in Pathfinder Brawler's Flurry should allow exactly the same number of attacks as corresponding {G,I}TWF feat does.
