### ISSUE TITLE
Flame Blade (Electric) Incorrect Number of Icons

### ISSUE THREAD

**Issue by Horologus** [Holic75/KingmakerRebalance#78]
When unrolling the Flame Blade (Electric) spell as a Storm Druid on the Quick Bar, the amount of icons is doubled (4 instead of 2).

https://imgur.com/a/OMunsYM

**Comment by Holic75** [comment]
This is correct behavior. 2 icons from spell itself + 2 icons from spontaneous casting, since technically it is not forbidden to spontaneously replace flame blade with another flame blade.

**Comment by Horologus** [comment]
Only this is not the case. When you click the "main hand" version of the spell, two icons light up. If you choose the "off hand" version, the other two do. There is no "spontaneous casting" version.
