### ISSUE TITLE
Occultist

### ISSUE THREAD

**Issue by decourcy2** [Holic75/KingmakerRebalance#85]
Occultist does not seem to work. 
Simple to see the problems. Start an Occultist, choose Transmute as a implement, dump 3 points into it, pop the strength button, you gain no strength. I thought maybe it does not show on the char sheet, so I went into combat to see if the bonus showed, it does not. 

Choose evocation, you gain elemental ray at 1st level. Should be 1 focus point fires one elemental ray, after choosing element, at opponent. It is permanently greyed out and unusable for me. 

Divination, put 2 focus points in at 1st level should give +1 perception divine bonus. I played until my first perception check, it was not applied. 

I am running this, your background trait mod and your proper flanking 2 mod.

**Comment by Holic75** [comment]
You need first to lock your distributed focus points, to get any effect from them. There is a corresponding button under focus distribution menu.
