### ISSUE TITLE
How to create a custom Feat?

### ISSUE THREAD

**Issue by Matnizak** [Holic75/KingmakerRebalance#9]
Hello, I would like to ask if you could point me somewhere where I could find a guide to create a custom feat. Specifically I want to add "Versatile Unarmed Strike" to my game to create a Scaled Fist/Duelist build. Is this feat to complicated to add, or will it actually be possible?

**Comment by Holic75** [comment]
no it is not complicated. There is a dedicated discord server, you can ask your questions there https://discord.gg/pathfinder-kingmaker
